public enum RequestStatus {
    NEW,
    IN_PROGRESS,
    REFERRED_TO_MANAGER,
    SYSTEM_PRICE_CALCULATED,
    MANAGER_PRICE_ADJUSTED,
    FINAL_PRICE_CALCULATED,
    PROPOSED_TO_CUSTOMER,
    DECLINED_BY_CUSTOMER,
    DECLINED_BY_MANAGER,
    APPROVED_BY_SYSTEM,
    APPROVED_BY_MANAGER,
    APPROVED_BY_CUSTOMER
}
